# slug=media CDN url (migrated to S3)
tactical-harness-set=https://dv0xg2r00n59r.cloudfront.net/products/tactical-harness-set.jpg
airtag-padded-harness=https://dv0xg2r00n59r.cloudfront.net/products/airtag-padded-harness.jpg
reflective-front-harness=https://dv0xg2r00n59r.cloudfront.net/products/reflective-front-harness.jpg
bungee-reflexive-leash=https://dv0xg2r00n59r.cloudfront.net/products/bungee-reflexive-leash.jpg
padded-nylon-leash=https://dv0xg2r00n59r.cloudfront.net/products/padded-nylon-leash.jpg
airtag-reflective-collar=https://dv0xg2r00n59r.cloudfront.net/products/airtag-reflective-collar.jpg
orthopedic-bolster-bed=https://dv0xg2r00n59r.cloudfront.net/products/orthopedic-bolster-bed.jpg
slicker-brush=https://dv0xg2r00n59r.cloudfront.net/products/slicker-brush.jpg
stainless-comb=https://dv0xg2r00n59r.cloudfront.net/products/stainless-comb.jpg
silicone-toothbrush-set=https://dv0xg2r00n59r.cloudfront.net/products/silicone-toothbrush-set.jpg
puzzle-mat=https://dv0xg2r00n59r.cloudfront.net/products/puzzle-mat.jpg
chew-module=https://dv0xg2r00n59r.cloudfront.net/products/chew-module.jpg
airtag-holder=https://dv0xg2r00n59r.cloudfront.net/products/airtag-holder.jpg
dog-goggles=https://dv0xg2r00n59r.cloudfront.net/products/dog-goggles.jpg
travel-water-bottle=https://dv0xg2r00n59r.cloudfront.net/products/travel-water-bottle.jpg
cat-reflective-harness-set=https://dv0xg2r00n59r.cloudfront.net/products/cat-reflective-harness-set.jpg
cat-printed-collar=https://dv0xg2r00n59r.cloudfront.net/products/cat-printed-collar.jpg
cat-wand-teaser=https://dv0xg2r00n59r.cloudfront.net/products/cat-wand-teaser.jpg
